In [ ]:
import pandas as pd
import numpy as np
!pip install geopandas
!pip install pyproj
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from google.colab import drive           
drive.mount('/content/drive')
%cd /content/drive/My Drive/Colab Notebooks/Final PRoject

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: geopandas in /usr/local/lib/python3.10/dist-packages (0.13.2)
Requirement already satisfied: fiona>=1.8.19 in /usr/local/lib/python3.10/dist-packages (from geopandas) (1.9.4.post1)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from geopandas) (23.1)
Requirement already satisfied: pandas>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from geopandas) (1.5.3)
Requirement already satisfied: pyproj>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from geopandas) (3.5.0)
Requirement already satisfied: shapely>=1.7.1 in /usr/local/lib/python3.10/dist-packages (from geopandas) (2.0.1)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (23.1.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (2022.12.7)
Requirement already satisfied: click~=8.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (8.1.3)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (1.1.1)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (0.7.2)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0->geopandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0->geopandas) (1.22.4)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pyproj in /usr/local/lib/python3.10/dist-packages (3.5.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from pyproj) (2022.12.7)
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive/Colab Notebooks/Final PRoject

In [ ]:
finalData = pd.read_csv("finalDataset.csv")
print (f" Final dataset shape: {finalData.shape}")
finalData.head(10)

 Final dataset shape: (32607, 28)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,neg,neu,pos,NearestStationLatitude,NearestStationLongitude,Distance,Subway_longitude,Subway_latitude,NAME,cluster
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75356,-73.98559,Entire home/apt,150,...,0.032255,0.107489,0.860256,40.75418,-73.98459,0.067703,-73.98459,40.75418,42nd St - Bryant Pk,6
1,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68535,-73.95512,Private room,60,...,0.017825,0.042350,0.939825,40.68138,-73.95685,0.288617,-73.95685,40.68138,Franklin Ave,6
2,5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.80380,-73.96751,Private room,75,...,0.008947,0.014396,0.976657,40.80397,-73.96685,0.036540,-73.96685,40.80397,Cathedral Pkwy (110th St),3
3,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Midtown,40.76457,-73.98317,Private room,68,...,0.064989,0.195013,0.739998,40.76457,-73.98073,0.128014,-73.98073,40.76457,57th St,3
4,5136,"Large Sunny Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66265,-73.99454,Entire home/apt,275,...,0.001492,0.008472,0.990037,40.66541,-73.99287,0.209688,-73.99287,40.66541,Prospect Ave,6
5,29628,"Comfortable, Sunny Room",127608,Chris,Brooklyn,Clinton Hill,40.68292,-73.96381,Private room,93,...,0.012857,0.090334,0.896810,40.68326,-73.96584,0.109184,-73.96584,40.68326,Clinton - Washington Aves,3
6,5586,Rooftop Deck/City Views. Great Apt,8526,Susan,Manhattan,Upper East Side,40.76076,-73.96156,Entire home/apt,295,...,0.002265,0.014253,0.983482,40.76271,-73.96738,0.333689,-73.96738,40.76271,Lexington Ave - 59th St,6
7,5803,"Lovely, Cozy, Room 1, BEST AREA; Legal Rental",9744,Laurie,Brooklyn,South Slope,40.66801,-73.98784,Private room,124,...,0.016266,0.077607,0.906127,40.67027,-73.98978,0.186300,-73.98978,40.67027,4th Av - 9th St,6
8,31130,Most Central Location!,117287,Lara Nicole,Manhattan,Hell's Kitchen,40.76720,-73.98464,Private room,200,...,0.142895,0.090895,0.766210,40.76825,-73.98193,0.159570,-73.98193,40.76825,59th St - Columbus Circle,6
9,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70935,-73.95342,Entire home/apt,81,...,0.036203,0.108343,0.855454,40.70689,-73.95349,0.169785,-73.95349,40.70689,Hewes St,2

In [ ]:
finalData.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license', 'neg', 'neu',
       'pos', 'NearestStationLatitude', 'NearestStationLongitude', 'Distance',
       'Subway_longitude', 'Subway_latitude', 'NAME', 'cluster'],
      dtype='object')

In [ ]:
Final_df = finalData.drop(['name', 'host_id', 'host_name', 'latitude', 'longitude', 'room_type', 'minimum_nights', 
               'number_of_reviews', 'last_review', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365',
               'number_of_reviews_ltm', 'license', 'NearestStationLatitude', 'NearestStationLongitude', 'Subway_longitude', 
               'Subway_latitude', 'neighbourhood'], axis=1)
#Drop columns that won't be included in recommendation system.

In [ ]:
Final_df.columns

Index(['id', 'neighbourhood_group', 'price', 'neg', 'neu', 'pos', 'Distance',
       'NAME', 'cluster'],
      dtype='object')

In [ ]:
Final_df.head()

,id,neighbourhood_group,price,neg,neu,pos,Distance,NAME,cluster
0,2595,Manhattan,150,0.032255,0.107489,0.860256,0.067703,42nd St - Bryant Pk,6
1,5121,Brooklyn,60,0.017825,0.042350,0.939825,0.288617,Franklin Ave,6
2,5203,Manhattan,75,0.008947,0.014396,0.976657,0.036540,Cathedral Pkwy (110th St),3
3,5178,Manhattan,68,0.064989,0.195013,0.739998,0.128014,57th St,3
4,5136,Brooklyn,275,0.001492,0.008472,0.990037,0.209688,Prospect Ave,6

In [ ]:
final_df = Final_df.rename(columns={'NAME': 'Station_name', 'cluster': 'Airbnb_type', 'neg': 'Rating Negative', 'neu': 'Rating Neutral', 'pos': 'Rating Positive', 'Distance': 'Distance_from_station'})

In [ ]:
final_df.head()

,id,neighbourhood_group,price,Rating Negative,Rating Neutral,Rating Positive,Distance_from_station,Station_name,Airbnb_type
0,2595,Manhattan,150,0.032255,0.107489,0.860256,0.067703,42nd St - Bryant Pk,6
1,5121,Brooklyn,60,0.017825,0.042350,0.939825,0.288617,Franklin Ave,6
2,5203,Manhattan,75,0.008947,0.014396,0.976657,0.036540,Cathedral Pkwy (110th St),3
3,5178,Manhattan,68,0.064989,0.195013,0.739998,0.128014,57th St,3
4,5136,Brooklyn,275,0.001492,0.008472,0.990037,0.209688,Prospect Ave,6

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32607 entries, 0 to 32606
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     32607 non-null  int64
 1   neighbourhood_group    32607 non-null  object
 2   price                  32607 non-null  int64
 3   Rating Negative        32607 non-null  float64
 4   Rating Neutral         32607 non-null  float64
 5   Rating Positive        32607 non-null  float64
 6   Distance_from_station  32607 non-null  float64
 7   Station_name           32607 non-null  object
 8   Airbnb_type            32607 non-null  int64
dtypes: float64(4), int64(3), object(2)
memory usage: 2.2+ MB

In [ ]:
ratings = final_df[["Rating Negative", "Rating Neutral", "Rating Positive"]]
ratings

       Rating Negative  Rating Neutral  Rating Positive
0             0.032255        0.107489         0.860256
1             0.017825        0.042350         0.939825
2             0.008947        0.014396         0.976657
3             0.064989        0.195013         0.739998
4             0.001492        0.008472         0.990037
...                ...             ...              ...
32602         0.001205        0.020151         0.978644
32603         0.001538        0.022110         0.976352
32604         0.001812        0.004688         0.993501
32605         0.001389        0.006860         0.991751
32606         0.001257        0.010110         0.988633

[32607 rows x 3 columns]

In [ ]:
ratingsRange = {"Negative": (ratings["Rating Negative"].min(), ratings["Rating Negative"].max()),
              "Neutral": (ratings["Rating Neutral"].min(), ratings["Rating Neutral"].max()),
              "Positive": (ratings["Rating Positive"].min(), ratings["Rating Positive"].max())}
ratingsRange

{'Negative': (0.0008454402, 0.98276806),
 'Neutral': (0.0044969753, 0.8831236),
 'Positive': (0.0020148277, 0.9936957)}

**Calculate compound rating score based on Ratings Negative-Neutral-Postive. First option: Scale the original compound scores to a normalized range of 1-5.**

In [ ]:
scoreWeights = {'Rating Negative': 1, 'Rating Neutral': 3, 'Rating Positive': 5}
compoundScore = ratings[['Rating Negative', 'Rating Neutral', 'Rating Positive']].mul(pd.Series(scoreWeights)).sum(axis=1)
#Multiply each ratings with corresponding weights and sum up.

#Scale the compound scores to a normalized range of 1-5.
rating1 = compoundScore.apply(lambda x: round((x - compoundScore.min()) / (compoundScore.max() - compoundScore.min()) * 4 + 1))

#Calculate the frequency of each ranking value.
ratingFrequency1 = rating1.value_counts().sort_index()
print(ratingFrequency1)

1      152
2      599
3     1094
4     6959
5    23803
dtype: int64

**Calculate compound ratig score based on Ratings Negative-Neutral-Postive. Second option: Rounding the original compound score to the nearest integer value.**

In [ ]:
scoreWeights = {'Rating Negative': 1, 'Rating Neutral': 3, 'Rating Positive': 5}

compoundScore = ratings[['Rating Negative', 'Rating Neutral', 'Rating Positive']].mul(pd.Series(scoreWeights)).sum(axis=1)
#Multiply each ratings with corresponding weights and sum up.

#Rounding the compound score to the nearest integer value. 
rating2 = compoundScore.apply(lambda x: round(x))

#Calculate the frequency of each ranking value.
ratingFrequency2 = rating2.value_counts().sort_index()
print(ratingFrequency2)

1      149
2      599
3     1092
4     7179
5    23588
dtype: int64

## **Compound reviews rating scores (choosing second option for recomendation system).**

In [ ]:
final_Data = final_df.copy()
#Create a copy to add reviews rating scores.
final_Data['Rating'] = rating2
final_Data.head()

,id,neighbourhood_group,price,Rating Negative,Rating Neutral,Rating Positive,Distance_from_station,Station_name,Airbnb_type,Rating
0,2595,Manhattan,150,0.032255,0.107489,0.860256,0.067703,42nd St - Bryant Pk,6,5
1,5121,Brooklyn,60,0.017825,0.042350,0.939825,0.288617,Franklin Ave,6,5
2,5203,Manhattan,75,0.008947,0.014396,0.976657,0.036540,Cathedral Pkwy (110th St),3,5
3,5178,Manhattan,68,0.064989,0.195013,0.739998,0.128014,57th St,3,4
4,5136,Brooklyn,275,0.001492,0.008472,0.990037,0.209688,Prospect Ave,6,5

In [ ]:
final_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32607 entries, 0 to 32606
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     32607 non-null  int64
 1   neighbourhood_group    32607 non-null  object
 2   price                  32607 non-null  int64
 3   Rating Negative        32607 non-null  float64
 4   Rating Neutral         32607 non-null  float64
 5   Rating Positive        32607 non-null  float64
 6   Distance_from_station  32607 non-null  float64
 7   Station_name           32607 non-null  object
 8   Airbnb_type            32607 non-null  int64
 9   Rating                 32607 non-null  int64
dtypes: float64(4), int64(4), object(2)
memory usage: 2.5+ MB

## **Recommendation System.**

In [ ]:
data = final_Data
data.drop(['Rating Negative', 'Rating Neutral', 'Rating Positive'], axis=1, inplace=True)
#Drop original three rating colummns. Put to a new dataframe 'data'.
data.head()

,id,neighbourhood_group,price,Distance_from_station,Station_name,Airbnb_type,Rating
0,2595,Manhattan,150,0.067703,42nd St - Bryant Pk,6,5
1,5121,Brooklyn,60,0.288617,Franklin Ave,6,5
2,5203,Manhattan,75,0.036540,Cathedral Pkwy (110th St),3,5
3,5178,Manhattan,68,0.128014,57th St,3,4
4,5136,Brooklyn,275,0.209688,Prospect Ave,6,5

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
def preprocessText(text):
  '''Return text in lowercase.'''
  preprocessedText = text.lower()
  return preprocessedText

vectorizer = TfidfVectorizer()
textFeatures = data['neighbourhood_group'].apply(preprocessText)
textVectors = vectorizer.fit_transform(textFeatures)
#Apply TF-IDF on 'neighborhood_group'.

In [ ]:
user_price = input("Enter price: ")
user_neighborhood = input("Enter neighborhood group: ")
user_rating = input("Enter rating: ")

Enter price: 200
Enter neighborhood group: brooklyn
Enter rating: 3

In [ ]:
recommendData = data.copy()

if user_price and user_price != "":
  user_price = float(user_price)
  recommendData = recommendData[recommendData['price'] <= user_price]
  #Obtain listings with price less than user's input.

if user_neighborhood and user_neighborhood != "":
  recommendData = recommendData[recommendData['neighbourhood_group'].apply(preprocessText) == preprocessText(user_neighborhood)]
  #Obtain listings in neighborhood group with user's references.

if user_rating and user_rating != "":
  user_rating = float(user_rating)
  recommendData = recommendData[recommendData['Rating'] >= user_rating]
  #Obtain listings has rating higher than user's input.

In [ ]:
#Create a user input vector.
user_input = [user_price, user_neighborhood, user_rating]
user_input_vector = vectorizer.transform([preprocessText(" ".join(str(x) for x in user_input))])

In [ ]:
#Calculate the similarity between the user input and listings features.
property_features = recommendData[['price', 'neighbourhood_group', 'Rating']]
property_feature_vectors = vectorizer.transform(property_features.apply(lambda x: preprocessText(" ".join(str(x) for x in x)), axis=1))
similarities = cosine_similarity(user_input_vector, property_feature_vectors).flatten()
similarities

array([1., 1., 1., ..., 1., 1., 1.])

In [ ]:
#Sort the properties based on similarity in descending order
indices = similarities.argsort()[::-1]
recommended_properties = recommendData.iloc[indices]

In [ ]:
# Display the top recommended properties
topRecs = 5  # Number of recommendations to show
recommendedIDs = recommended_properties['id'].head(topRecs).tolist()
print(f"Top {topRecs} recommended properties:")
for listingID in recommendedIDs:
    print(f"- Property ID: {listingID}")

Top 5 recommended properties:
- Property ID: 838548659003355204
- Property ID: 18908638
- Property ID: 20209878
- Property ID: 20089288
- Property ID: 20085462

In [ ]:
#Display the top recommended properties with station name and distance.
topRecs = 10  
#Number of recommendations to show.
recommendedIDs = recommended_properties['id'].head(topRecs).tolist()
print(f"Top {topRecs} recommended properties:")
for listingID in recommendedIDs:
  stationDistance = recommendData.loc[recommendData['id'] == listingID, 'Distance_from_station'].values[0]
  stationName = recommendData.loc[recommendData['id'] == listingID, 'Station_name'].values[0]
  Airbnb_type =  recommendData.loc[recommendData['id'] == listingID, 'Airbnb_type'].values[0]
  print(f"- Property ID: {listingID}, Distance to Nearest Subway Station: {stationDistance:.3f} miles, Nearest Station: {stationName}, Airbnb Type : {Airbnb_type}")

Top 10 recommended properties:
- Property ID: 838548659003355204, Distance to Nearest Subway Station: 0.144 miles, Nearest Station: Wilson Ave, Airbnb Type : 6
- Property ID: 18908638, Distance to Nearest Subway Station: 0.251 miles, Nearest Station: Ditmas Ave, Airbnb Type : 6
- Property ID: 20209878, Distance to Nearest Subway Station: 0.321 miles, Nearest Station: Kingston - Throop Aves, Airbnb Type : 6
- Property ID: 20089288, Distance to Nearest Subway Station: 0.144 miles, Nearest Station: Cypress Hills, Airbnb Type : 3
- Property ID: 20085462, Distance to Nearest Subway Station: 0.326 miles, Nearest Station: Kingston Ave, Airbnb Type : 6
- Property ID: 20285258, Distance to Nearest Subway Station: 0.079 miles, Nearest Station: Union St, Airbnb Type : 2
- Property ID: 20073959, Distance to Nearest Subway Station: 0.200 miles, Nearest Station: Crown Hts - Utica Ave, Airbnb Type : 6
- Property ID: 19949403, Distance to Nearest Subway Station: 0.092 miles, Nearest Station: Marcy Ave, Airbnb Type : 3
- Property ID: 19949138, Distance to Nearest Subway Station: 0.539 miles, Nearest Station: Carroll St, Airbnb Type : 6
- Property ID: 19944880, Distance to Nearest Subway Station: 0.327 miles, Nearest Station: Bedford Ave, Airbnb Type : 6

In [ ]:
recommendData[recommendData["id"]==23821517]

,id,neighbourhood_group,price,Distance_from_station,Station_name,Airbnb_type,Rating
10965,23821517,Brooklyn,126,0.103231,Prospect Ave,4,4

## **class for Recommendation system.**

In [ ]:
class RecommendationSystem:
    def __init__(self, data, vectorizer):
        self.data = data
        self.vectorizer = vectorizer

    def preprocessText(self, text):
        '''Return text in lowercase.'''
        preprocessedText = text.lower()
        return preprocessedText

    def recommendListings(self, user_price, user_neighborhood, user_rating, topRecs=10):
        recommendData = self.data.copy()

        if user_price and user_price != "":
            user_price = float(user_price)
            recommendData = recommendData[recommendData['price'] <= user_price]

        if user_neighborhood and user_neighborhood != "":
            recommendData = recommendData[recommendData['neighbourhood_group'].apply(self.preprocessText) == self.preprocessText(user_neighborhood)]

        if user_rating and user_rating != "":
            user_rating = float(user_rating)
            recommendData = recommendData[recommendData['Rating'] >= user_rating]

        #Create a user input vector.
        user_input = [user_price, user_neighborhood, user_rating]
        user_input_vector = self.vectorizer.transform([self.preprocessText(" ".join(str(x) for x in user_input))])

        #Calculate the similarity between the user input and listings features.
        listing_features = recommendData[['price', 'neighbourhood_group', 'Rating']]
        listing_feature_vectors = self.vectorizer.transform(listing_features['neighbourhood_group'].apply(self.preprocessText))
        similarities = cosine_similarity(user_input_vector, listing_feature_vectors).flatten()

        #Sort the listings based on similarity in descending order.
        indices = similarities.argsort()[::-1]
        recommended_listings = recommendData.iloc[indices].head(topRecs)

        #Display the top recommended listings.
        print(f"Top {topRecs} recommended listings:")
        for _, listing in recommended_listings.iterrows():
            listingID = listing['id']
            stationDistance = listing['Distance_from_station']
            stationName = listing['Station_name']
            Airbnb_type = listing['Airbnb_type']
            print(f"- Listing ID: {listingID}, Distance to Nearest Subway Station: {stationDistance:.3f} miles, Nearest Station: {stationName}, Airbnb Type : {Airbnb_type}")

In [ ]:
recSys = RecommendationSystem(data, vectorizer)

userPrice = input("Enter price: ")
userNeighborhood = input("Enter neighborhood group: ")
userRating = input("Enter rating: ")

#Recommend listings based on user inputs
recSys.recommendListings(userPrice, userNeighborhood, userRating)

Enter price:
Enter neighborhood group:
Enter rating: 4
Top 10 recommended listings:
- Listing ID: 839119919829213270, Distance to Nearest Subway Station: 0.049 miles, Nearest Station: Fulton St, Airbnb Type : 6
- Listing ID: 23021271, Distance to Nearest Subway Station: 0.187 miles, Nearest Station: Elmhurst Ave, Airbnb Type : 6
- Listing ID: 23821517, Distance to Nearest Subway Station: 0.103 miles, Nearest Station: Prospect Ave, Airbnb Type : 4
- Listing ID: 23821848, Distance to Nearest Subway Station: 0.257 miles, Nearest Station: Bedford Ave, Airbnb Type : 6
- Listing ID: 23661749, Distance to Nearest Subway Station: 0.125 miles, Nearest Station: Clinton - Washington Aves, Airbnb Type : 3
- Listing ID: 23826739, Distance to Nearest Subway Station: 0.182 miles, Nearest Station: Broadway, Airbnb Type : 5
- Listing ID: 23545793, Distance to Nearest Subway Station: 0.168 miles, Nearest Station: Canarsie - Rockaway Pkwy, Airbnb Type : 6
- Listing ID: 23666777, Distance to Nearest Subway Station: 0.548 miles, Nearest Station: Nereid Ave (238 St), Airbnb Type : 3
- Listing ID: 23560187, Distance to Nearest Subway Station: 1.039 miles, Nearest Station: Canarsie - Rockaway Pkwy, Airbnb Type : 2
- Listing ID: 23838063, Distance to Nearest Subway Station: 0.194 miles, Nearest Station: Central Ave, Airbnb Type : 3

In [ ]:
recommendData[recommendData["id"]==23821517]

In [ ]:
import pickle

In [ ]:
pickle.dump(final_Data, open("BNB.pkl", "wb"))

In [ ]:
!pip install flask

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: flask in /usr/local/lib/python3.10/dist-packages (2.2.4)
Requirement already satisfied: Werkzeug>=2.2.2 in /usr/local/lib/python3.10/dist-packages (from flask) (2.3.0)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.10/dist-packages (from flask) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.10/dist-packages (from flask) (2.1.2)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.10/dist-packages (from flask) (8.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=3.0->flask) (2.1.2)

In [ ]:
# Took way too long to run, thought to drop it off

from flask import Flask, render_template, request
import pickle

app = Flask(__name__)

# Load the recommender system object using pickle
with open('BNB.pkl', 'rb') as f:
    recommender = pickle.load(f)

# Define the routes and views
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/recommendations', methods=['POST'])
def recommendations():
    # Get user inputs from the form
    user_price = request.form.get('price', '')
    user_neighborhood = request.form.get('neighborhood', '')
    user_rating = request.form.get('rating', '')
    top_recs = 5

    # Call the recommendListings method of your recommender system
    recommendations = recommender.recommendListings(user_price, user_neighborhood, user_rating, top_recs)

    # Render the recommendations on the results page
    return render_template('results.html', recommendations=recommendations)

# Run the Flask app
if __name__ == '__main__':
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off

INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit